name: test
on: [push, workflow_dispatch]
jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - name: run test
        uses: mike-neck/action-pixela-increment
        with:
          user: mike-neck-hatenadiary-com
          graph-id: gh-action-test
          token: ${{ secrets.PIXELA_TOKEN }}
